travis:
  secure:
    BINSTAR_TOKEN: YIL1QdNuCZVLaj8NUDhDhW8ZbayWalGFgY4X5M76F6IKetAlDmRwiu31Fjj4DBsDh0e+eOSnedR9WZxn/f4Ke9yjIKvePfVN8sbB1MryrSPnJCIjn292cmrQdVkYaNwrI0mrVsP31+K33GIHqcPaLbx5RatcBJjKZ/NP9Q736gjc1Gkg7nmhOuaqavw9eB/7mPXej2Q7hqkgiYsfQmkegTQ7CsaWBjJbW/JjBwX47XUOX7QfscOqQ8VJuBGJmLQXjIuD5mHzeh7w4r9J3e3QmfWA5PoXSW0zJdqZTfIF584tdueBnJL+lZcd7oJEk/25azzB9Dxivug3b3RjR9RQ1OSiF5YJtCrZbA5X3T2qZc5JRTeUzmhIq4sMt3D/uKo8+fqmLHB6JukuR5ozztSGPqzSTUvh7eAB1CtJdXe8TbhMp9AnypMvBjMNzodvEgQMgkylyCgo5kpLKc+F627CxQU7+Wew85jDQQqn8P+YYiEl60DyxXIBHPFx4c9cGsLsTf3OZIo5d6UedQizmnY63Zpd2eTLA1pIiurOPGasRHQy+jmepPZgb0sbmlQ2z6TqpeQXy6dzPbF6Drh7aaD6jDmNNBf0gtlAnq8dw0WRpjlW45ob+Buyw43z3zAZN2jNX1KL0jemI1D9UghDYFQBY2h9MbAHNHxWbvkblnp8nYU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
