travis:
  secure:
    BINSTAR_TOKEN: e6Y00AaFmZb57MaGwQjnjgRiImRUksQUB2TWPMtn5NrhN4k82/tmbc/minN9JgsvDVhjhBbFwK3O6rsmehaKihDZQBKaVscvRVvU36ccdAHGrnJ5qw5LFsU8+9ZJUaY1qiqJw3djLRDFQsN79nPXJ1z4Vqocx1JXfyZgyArBvynUmOu1qO5rpPkGQXoMARgnTS1tx7kVjF9gI8XUQgpUfIPOPU2sJ2mbkRsPoXC+g3aW65bjii3aopGhL4tIVRZVxCU9P885tOiuygQkAo7l4BoGgn9PWzFobcYkuY5lIRcT/zrq7AiGphF8M7M/GlLn+qnuwn5rJsDT8hPBgLRI35De5izB5C4u9kIbJoupPpoOInBLkqPXanPZGQUy2NMTQzMKUh0OjLsO65x4nz/TzzqBovyeubTVt3UiC0O8N4FAiB40LzWcXPVAUbhO92Ko4sd2mAmE40cwUgnqK6xu9V5ZGVRKk9Q4D1+RaKVm+A6oV2FJ6mE0ZQLdGU/mGulvvOi8z0m88JeZj7fuXvD1GKJg8keDTlz7pID9gGw30mvldOoRVx5etLJOgGaE17yKAwGdpbIbnzA3xhBe4kfASZatob0VDn8+7FzYgBzdJmrei1vHDlKyLb/Z+zNfEqWvAXp2bIWZh2eYR/KPFpBBzefY8/9voUuHz7On0l3IJiE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
