travis:
  secure:
    BINSTAR_TOKEN: G9GrrvQrX/SYVyU8v0bHdnN9H6ri6Zu3baEMNGK1+XZRq49R/7fpZkMbDxsntp9NISfQLOHw0xDmK2pKipyAdHRLEY4M7LbEdW6+S0M0y9mWD/kKF1IicMKT+Dm0ukH5OYn8UIloq0csMI936+mWQ7QFZqZ4VOxp0vBMhy0InPLgxPte9cJdqFnAtqwcmus5t1GY5Td93xSIs/XIs2swKuSJsBmoO0HUynOYs2kjgmCGy0zOTCoJHTpebfpNAoTER+18+lDYW2L9pkb61fZcHE5GNYhicao8ccgUv8QFij2ODIVZhuxRW1T+lwMrsMAUksNsMUmjoG8VKxsW3thoBe8DQ3Kq97fjbN9yn+thqrS4hKMbvrDI/UX7adzFIUONu4Sgv67rGtK+n6oGJ08IHD3dgJ/fUR3tuMeqevaTAfDiDa1UzmDrVqqE7DRVwqImIKP4Xgw52/DWLxw4BHwDbt6DISuFDpCUz04qijj1eJQ1eMkeJwsJ14pOQUcvD0Y65xz5JHcZakmt7Z+czPzLeWOcOUAbbtPfVlnl4Pu5ZpcR5S97f+5Vf2M6LUsW3cG/GAmEIoltjJqo+SuL6MKe+JDwKTkk/GCjwqQWyHv2ON82hBo4VmDKVK4sxwg5YFNpm4yGEHdsd1S33c+M5awQTVCiEOwYRPEyQDLP26NVQpQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
