travis:
  secure:
    BINSTAR_TOKEN: MpUEDP0m2ZlhXeW5sml8BSIoYVjk+dfz/LWOFrck7XKvwutSMHNwBRPQxHc+6c77Ujsjs6RX1/3LXg4VFY+WOtXNOqELPMNy5Jmue0Jgh8rN8fImXttCYHF04/N4iDVN5n9j2jm+QTOZkPcgAzOFUQiYG/dGX6RF/6tRyKtev9CNoxH+ZFjQ72xDYCDHawCgNekf/4fT2iFg5U8Z3MiBlXdVc0dCT9kOC+QrsjvYMaa/fT6PHKupbGEuXlj/q783bSANORXGnr+SMeM0W3Cw2mo0IYIStHWDaRxY8q6ppGJPSoujyTldln73D41grrhUHPCRSEiZGy2xFmgr/EP1GEsUANmLSo5GsOzu3DbcgrdSwPDed84ir+KxIsaDCon1tPg13uR2sOe/9amPJztMgaMKJLwB/njt5NnyGfwJ9xZQrjq0mOH6NWXGpIU8vYgkHYmFZUiHD/tS8UfLG4V/BkJh+LQhsX/tcKgIV8/7b9iVDyJAL8iPorYcbzSgpf+Q3AJQrRXdWKj7Mab0JeYKpejHdpnaKRvDeVoBrCJejOo+K/nDHmyk7PduxAAxepfOii9Vt3cdayqAh7kq6ckw2ykDvvUyE0+91QBhJodY7JNSDV6OLz+WEvOMK8XqjY3SCa3WgwGMe8bkO88QsV+w4rBz6GIJ5tyjuiD4ETbPWS8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
