travis:
  secure:
    BINSTAR_TOKEN: ZgwvUW8x4bdujcs8lNpr1u0d8ET1lOQmThPRnvp8muSCvtlMo0BaQUsZQ9iLCCygtZUg22dQq8KBUUHmIx2/QKAHc7xFK/bJreYZuFRJRKFZDUmtMlfsUsM5S24VnW9HkBUrJEfyfzydptNvE67RCDdmo8e5EAKkcm7dG4fAQJVOCBFB3ycdzM9DcvFPyxvSS1Efg21Oq8qa4sj0b1tA0VID8D/2Bm7yrkq9VWbzUL8oCeKHUMSrRju2lbsSckoGXwyZFdNkjVDxV+pDDorsG1LQeMBOzecByzYRPNKIiyQXtaJUwRoIvF1xsIdMPdKhKAszlmLdL+RS+DxtuY2xO9KYXHW3U8Yzu88LIDDxrM3+c2x4FrIUbLLizVesrzr1fNyfbqho6oHr9au+BS/8zXZgwCX+uAWP8BhRJLVNHDQtq9B1QIKW0Z6suscj/sMNLR2MB6202q1ms+awl89JNn0ALaFXw1tmZ+NRGkQWasIrfoIwXZhL46jJSiH+lodLuPXSC9EaHngxVgNGwy35mtjFa5qtEaxr0GoVYjxTJvVbBxjXiPV1V1+qxGk1s7M8w5sYk9E5UwJ19fe2V1VUocw04aqs98efvk2QjI3xZLqbV7yB3TfAl8z/d/Db88+2DvGNnG51IWYN19LfizMAVsBZqe9QVh9ebSlnZSKeGpM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
