travis:
  secure:
    BINSTAR_TOKEN: SHZJ0LDiDgXZ5a/To1EPdDY7731ez+WDZSA+sZ4tnLTIRbjYN+5ASBaSfblr+HLjdnYpk38fao7pVGhF3yct8uQyDlRXBMAp/k3oiXWpK+iwTd01fhl3pyYbn1RSxwslsvN/w0duDLiRYtoVVaSfjHH/VibhtwDgGlknjiMYw7PRIRWHTwC1dsMg8iMJbE4cf3PfQMBJpar4rWpM8cQ5XmNHmVEJqizeXyU7HcYYnZycIo0aK48iW3+RUTh7gWHe4c5U70eyWjf9bbWrVvTEEpaOtrKOSA4L//28iWgnIk6mYV3cw2fZBVyVdP450qVvXTY1GQz2AZb2sxSQdCi4R+WPNh5m933/8zgRbA4ZWjp7GpawPZJClJCVRCUWUHmYTnOC3973gD9rqtGho1gruEl5f90oLfE8f60M+cpvHzDHHNYMl9ZsoGj635YompkC3eHpQXVLHgCfJb+CgZUCzK8QTCcT4X6JGrY8/nQjvitnB9TToRRy3HJ5C9StzeZrQcDoYFllP64wyr3RZNPBNbXl26CpGQanQN/giP1HFGtiOzcOLB2b28r8fYgXtVeWOZhd2+1/DTfzIMHYFWW9G8K8ShgjXB9fR4vLHLfnZfw8ENYDq2l/aCSt6x6zd6joVULtytdPhNLT1ZiRR2h+BEz0WEyd0H+1jbVosx1c9c4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
