travis:
  secure:
    BINSTAR_TOKEN: gOKljrqKudfKAgmO2I9zrn5VYmrGtUk6q6HRIq1RdbRXJdV/c+VXVBN+aZ38grWU9I9zLkWeofZgPGTet7uG05pf0HDEo/OlYEC2fLbID0YdWFtQ1biCiny6s6jVLtrYmcZqzgEnklDQAfLv3d455qEKH2VEZeujE7Aqgq7tAH8OcAPmh959ca26mVqjQzD7fVnMDAlsfjnuhcvg6Sw3mgxfparyEc4r06pIsaSaIR9JmjVkp0SiNwbUscs/+N8vGh65N2j5J311FRlyNz7SBZ3Rip+JmrdsxtMr2DRZb7xA9W18xA/iOxpwuZZ/gIm68v3T2/Bt3S2Gif26rgyjLmuuAMGr5ttcjr/tiO6FP8QmifnLVrk52Ibuf5exILFd3Day28z6/Vyovp3R26N1RmqHqmz83NpKVv7sJgSxFujnuHOsGMZevCstnfeySVaapffd64rS+67WXtLw3HsqDrrg++CMKMc9G1hZD30bsRi3MRBjtGQfktMU7O3B/JSlktVFPqtGX0jKtuPSjfMtR1KsPzxBE8C+UkglnuT/zD/WKKjbTYl9LOvM5/kYjUpraetdHahak3WpYK3br7Z5YWitwBOxhVUhue3pcT0HRR9gie9Q4vpVJXX9Fu2rVShwraoZMtgesn1FzwKo8GWbj4GNa4wlmnGZpFvQKWbkUlU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
