travis:
  secure:
    BINSTAR_TOKEN: Ap5eATb2quiy6c+vavLzW0rWxk/9gL4NQhIsKFKP+XNWrmARvztjeQcJsX9D2JPUWIE1XMNorZ0fVmAnEbebe8vs1ovDx/G2C+EsblNZeNFbajFRpLROXdrPABgDlszP8fMIvVWXZZRrQoiPxqjKDFQ2aJQZ4QiDUVshFP1kVIoB6gO9glASC3PTnS+FmwXUz2O9KkSi/H2uUNUc3DylwgjdPaxshWk6RhAug4sLXBEd36/IH8Svjj1cXPykCbhkPwXpSvigkYIvdJWNQTSqi9NLPqhBAU4SQPaIsWxByjqSNfYjXywJnfwCYrBiLXOxpPARytAw8gWrpSyt/eVqK/uNKfxUOYQTcbA/cqUc0+3/C1szMVQPlPmXwFGecSnRRo4wuNHEsqJzzj4wwYqhgyRlavrh1n9KqTjSGQhou3yspvrAmLdLVxgHhHpDJv6aTOEsz+GTjl72FKlr0S3vGOkasnQAelcE2rL2dlfQCKd1FTqpn8ucKXEF5D4/KBAzP0iYqKkfNFtegeANtpxRSZiv50rvoNLVyg9ENKFq9P3GVfbj3Ji+wg0z2rbp8Aa6hDxrD61oLvimlfJMuWckW/U0JTYdtHigsuI/JVDUseVRPNIWaVfvK57kRs9CFz+4NT43IH0OZN6wR8JmrU6J8vCLi9896cBx7U4fFNedp1E=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
