travis:
  secure:
    BINSTAR_TOKEN: VgCn81u3UK3T7XhwNJvK/aiUI7J0EXV9OCd2tcM1Q7eiQPD1Uf0h3nUUKlDfk4rS2mF6PdEOROq+jIKlT85OarUSXg4wAmlr7QSxRvBA1HNSGfqW1OrIK7aNSS7QH9cZvKZ83VSiDXVFOjVmktDWygIrzeH5T/VR+7jj0aPbPqeGSDwXd0a8HggqENjgtu5cw9yLnTaqWu/g9WAxz4DmgVVe6yDxixFYvbqcWUbNcZgf5Ud17bLLbHtDu0znlXKzHKg1mPWCZSmMIZMPeeoQl9iKW9oq5fet8HOwfLiUllnGelfaTltkbqe1L50TBy/SYvwML4hgU4GvTcE1G0YZZS6zZIGvdBNV+XDm4hvT7/4aD0kbt+PNS0333C0mdKmVbviAowow7aufxNY8gdVc8v6SdPxPkJk/PQqgJdQI12tZIYPBlAe8RUSAf17rMcc0/MyOP5RDOyEnZJu3AOf3CUYQ5ikH0MmLm4VQDDGs+DLmtaN6suvtvTPH0rbLh4NRdO/3GIX87X4voF8h6T6CtDM9gVekdlBVglYvJx+3L14z0u5EGFR7nZAEbMvXKIX0uc6M7YBrAZxaS8/Cc4bLklkyc/sxmAhsP3XtMQ8RZO2amCq41YSmsXG4zkq0pgtODuc4VTVPcEtRRZ0t/Rs30ZyYy/W0LbsNhkSyQg9mAI4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
